### ISSUE TITLE
matches? for IFn keys in the pattern.

### ISSUE THREAD

**Issue by samirsa** [Invocatis/motif#3]
thanks for a cool concept. 

Just thought about posting an issue about some error in the example for IFn keys

(matches? {:key 1 #(count (keys %)) 1} {:key 1}) 
It seems that the output should be true. But it shows false for me. 

Similar error for (matches? {pos? false neg? false} 0) as well

Thanks,

**Comment by Invocatis** [comment]
Hey Samirsa, thanks for raising the issue.

I think my clojar deployment and source code must have gotten out of sync. I'm still getting used to the ideas of git flow and deployment responsibility. 

As is such, I've release 0.1.1 to address this. I've checked the examples listed and they seem to work.

Thanks again
